name: reftest

channels:
    - http://ssb.stsci.edu/conda-dev
    - http://ssb.stsci.edu/astroconda
    - astropy

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sqlalchemy
    - jwst
    - stsci_sphinx_theme
#   - pip:
#       - dependency_from_pip
